spring.application.name=SavingAndLoanRepaymentTracker

# ==============================
# DATABASE CONFIGURATION (from environment variables)
# ==============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATE CONFIGURATION
# ==============================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}

# ============================
#      Allowed  origin
#=============================
application.allowedOrigin= http://localhost:4200,http://10.1.22.72:4510,http://localhost:8085
#constatnt
application.annualInterset=0.07
application.period=10
application.annualPeriod=12
# ==============================
#  JWT CONFIGURATION
# ==============================
application.jwt_secret_key=MzI2Yml0c2VjdXJla2V5MzI2Yml0c2VjdXJla2V5MzI2Yml0c2VjdXJl
# Change this to a long, random string in production
application.jwt_expiration_time=3600000
# 1 hour in milliseconds


server.max-http-request-header-size=20000

# =========================
# MANAGEMENT ENDPOINTS
# =========================
management.endpoints.web.exposure.include=health,info,prometheus

# METRICS
# =========================
management.metrics.tags.application=${spring.application.name}


# TRACING CONFIGURATION
# =========================
management.tracing.sampling.probability=1.0

# OPENTELEMETRY (OTLP)
# =========================

management.otlp.metrics.export.url= http://host.docker.internal:4318/v1/metrics
management.opentelemetry.logging.export.otlp.endpoint=http://host.docker.internal:4318/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=http://host.docker.internal:4318/v1/traces
logging.level.enat.bank =debug
logging.level.org.springframework.security= DEBUG
logging.level.spring.jackson.serialization.ail-on-empty-beans=false:
# ==============================
# LOGGING CONFIGURATION
# ==============================
logging.level.org.springframework=INFO
logging.level.com.yourcompany=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n


#eureka.client.service-url.defaultZone=http://10.1.22.72:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=true
# ==============================
# SPRING DOC / SWAGGER (optional)
# ==============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
