spring.application.name=Saving and Loan reapayment Tracker
server.port=8085
# ==============================
# DATABASE CONFIGURATION
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/repaymentsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=yosi4321@A
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATE CONFIGURATION
# ==============================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true
# ============================
#      Allowed  origin
#=============================
application.allowedOrigin= http://localhost:4200,http://localhost:4500,http://localhost:8085
# ==============================
#  JWT CONFIGURATION
# ==============================
application.jwt_secret_key=MzI2Yml0c2VjdXJla2V5MzI2Yml0c2VjdXJla2V5MzI2Yml0c2VjdXJl
# Change this to a long, random string in production
application.jwt_expiration_time=3600000
# 1 hour in milliseconds

# ==============================
# LOGGING CONFIGURATION
# ==============================
logging.level.org.springframework=INFO
logging.level.com.yourcompany=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n

# ==============================
# SPRING DOC / SWAGGER (optional)
# ==============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
