spring.application.name=Saving and Loan reapayment Tracker
# ==============================
# DATABASE CONFIGURATION
# ==============================
spring.datasource.url=jdbc:sqlserver://10.1.12.75:1433;databaseName=moenco_sacco;encrypt=false
spring.datasource.username=Mtesfa
spring.datasource.password=Mtesfa@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# ==============================
# JPA / HIBERNATE CONFIGURATION
# ==============================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.jpa.properties.hibernate.format_sql=true
# ============================
#      Allowed  origin
#=============================
application.allowedOrigin= http://localhost:4200,http://10.1.12.70:4510 ,https://saccos.enatbanksc.com/
#constatnt
application.annualInterset=0.07
application.period=10
application.annualPeriod=12
# ==============================
#  JWT CONFIGURATION
# ==============================
application.jwt_secret_key=MzI2Yml0c2VjdXJla2V5MzI2Yml0c2VjdXJla2V5MzI2Yml0c2VjdXJl
# Change this to a long, random string in production
application.jwt_expiration_time=3600000
# 1 hour in milliseconds

# ==============================
# LOGGING CONFIGURATION
# ==============================
logging.level.org.springframework=INFO
logging.level.com.yourcompany=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n

# ==============================
# SPRING DOC / SWAGGER (optional)
# ==============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
